version: "3"
services:
  # Deploy-Code Service
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app_network

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    networks:
      - app_network

  process-video:
    container_name: process-video
    build:
      context: ./process-video
      dockerfile: Dockerfile
    volumes:
      - ./process-video:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    networks:
      - app_network

  database:
    container_name: postgresDB
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:  # Define the named volume here


# Todo Part 
# Change the port