# Multi Stage Build for Bun to optimise the size of the docker image
FROM oven/bun:latest as Builder 

WORKDIR /app

COPY bun.lock .
COPY package*.json .
COPY tsconfig.json .

RUN bun install

COPY . .

RUN bun build ./index.ts --outdir ./build

FROM oven/bun:latest as Runner

COPY --from=Builder /app/build .

CMD ["bun", "index.js"]
