apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1  # Start with 1 replica for testing
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hls-apaptive-bitrate-system-backend  # Must match local Docker image name
        imagePullPolicy: Never  # 🚀 Prevents Kubernetes from pulling from Docker Hub
        ports:
        - containerPort: 80
